// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-directions/Depth.tsx": () => import("../components/mockups/portfolio-directions/Depth.tsx"),
  "./components/mockups/portfolio-directions/Editorial.tsx": () => import("../components/mockups/portfolio-directions/Editorial.tsx"),
  "./components/mockups/portfolio-directions/Orbit.tsx": () => import("../components/mockups/portfolio-directions/Orbit.tsx")
};
